spring:
  application:
    name: snow-personal-admin
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    jdbc-url: jdbc:mysql://39.108.61.242:3306/personal_admin?characterEncoding=utf-8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root #Yls147258
    driver-class-name: com.mysql.jdbc.Driver #com.mysql.cj.jdbc.Driver
    hikari:
      #maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 300 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
      connectionTimeout: 30000
      idleTimeout: 30000
      validationTimeout: 3000
      loginTimeout: 5
      minimumIdle: 10
      #connection-test-query: SELECT 1
  redis:
    database: 0
    host: 39.108.61.242
    port: 6379
    password: redis6379
    timeout: 10000ms
    lettuce:
      pool:
        max-active: -1
        max-idle: 15
        max-wait: 1000ms
        min-idle: 0
      shutdown-timeout: 100ms
    sentinel:
      master: mymaster
      nodes: 39.108.61.242:26379,39.108.61.242:36379,39.108.61.242:46379
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    mode: LEGACYHTML5
  #aop:
    #proxy-target-class: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: org.springboot.sample.entity
  typeAliasesPackage: com.github.ciifm.personal.admin.dao.dataobject
  keyGenerationMode: CUSTOM

server:
  port: 8080
  session-timeout: 60
  tomcat:
    max-threads: 800
    uri-encoding: UTF-8
  error:
    path: /error

octopus:
  file:
    accessKeyId: LTAIvvi58X53DhiP
    accessKeySecret: RduYpUIMhFKtKwu9VRSgBThag4h5xy
    cloudType: oss
    endpoint: http://oss-cn-shenzhen.aliyuncs.com
    publicBucketName: youlv-public
    privateBucketName: youlv-private
    expire: 10


